can_i_apply:
  title: ¿Puedo aplicar?
  content: |
    ¡Sí, tu puedes! Aceptamos nuevos estudiantes cada 3 años, después de la promoción actual se ha graduado. Sin embargo, solo unos pocos estudiantes son aceptados para estudiar en nuestro instituto.
    
    Debes aprobar nuestra prueba y calificarte respondiendo una entrevista de nuestro comité de admission. Abajo encuentras más detalles sobre ese proceso.
how_to_apply:
  title: ¿Cómo puedo aplicar?
  content: |
    Acceptaremos aplicaciones en **verano 2019**, cuando la promoción actual se ha graduado. Hasta ahora, no se puede aplicar, pero tu puedes prepararte. Abajo encuentras los requisitos de admission.

    ¿Más preguntas? Ponte <a href="/contactenos/" class="text-link">en contacto</a> con nosotros y te ayudaremos pronto.
process:
  title: El proceso
  items:
    - Tomar y aprobar las pruebas de admission al Instituto<sup>1</sup>. Eso incluye un exam de admission de matématica, física y espanol.
    - Entrevista con el Comité de Becas y el Departamento de Orientación
    - Una semana de convivencia en el campus de la escuela.
    - Despues de la semana te avisamos si te cualificaste para estudiar en el Instituto
    - En septiembre, el primer cuatrimestre comienza
  footnotes:
    - Si es menor de edad, asistir en compania de sus padres o tutores.
requirements:
  title: Requisitos para aplicar
  content: "Antes de aplicarte al Instituto, segurarte que tienes la siguiente documentación:"
  items:
    - Formulario de Solicitud de Admisión
    - Dos fotografías 2" x 2" de frente y recientes
    - Acta de nacimiento certificada
    - Copia de cédula de identidad y electoral o pasaporte
    - Certificado oficial de Bachiller
    - Record de notas oficial de Bachiller
    - Recibo de pago del derecho a admission
    - Certificado médico
    - Certificado de no antecedentes penales
    - Una carta de recomendación de dos profesores del centro educativo origin.
    - Ser dominicano o haitiano, en el caso de los solicitantes a programas de beca