backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "images/"

collections:
  - name: "carreras"
    label: "Carreras"
    folder: "_carreras"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "careers" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "config"
    label: "Configuración"
    files:
      - name: "redes"
        label: "Redes Sociales"
        file: "_data/social.yml"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Text", name: "text", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }