backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "images/"

collections:
  - name: "carreras"
    label: "Carreras"
    folder: "_carreras"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "careers" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }
